[Sariel]
name = "Sariel"
race = "Elf"
cclass = "Ranger"
level = 4
max_hp = 32
cur_hp = 32
ac = 16
initiative_mod = 4
image_url = ""

[Sariel.senses]
perception = 15
darkvision = 60

[Lander]
name = "Lander"
race = "Human"
cclass = "Fighter"
level = 4
max_hp = 36
cur_hp = 36
ac = 17
initiative_mod = 0
image_url = ""

[Lander.senses]
perception = 14

[Armek]
name = "Armek"
race = "Dwarf"
cclass = "Cleric"
level = 4
max_hp = 38
cur_hp = 38
ac = 18
initiative_mod = 0
image_url = ""

[Armek.senses]
perception = 13
darkvision = 60

[Pip]
name = "Pip"
race = "Halfling"
cclass = "Rogue"
level = 4
max_hp = 29
cur_hp = 29
ac = 16
initiative_mod = 0
image_url = ""

[Pip.senses]
perception = 10

[Dewain]
name = "Dewain"
race = "Elf"
cclass = "Wizard"
level = 4
max_hp = 30
cur_hp = 30
ac = 14
initiative_mod = 0
image_url = ""

[Dewain.senses]
perception = 13
darkvision = 60

[Elwing]
name = "Elwing"
race = "Human"
cclass = "Fighter"
level = 4
max_hp = 38
cur_hp = 38
ac = 16
initiative_mod = 0
image_url = ""

[Elwing.senses]
perception = 13
